name: Build and Release 2

on:
  push:
    #branches:
    #  - main
    #  - beta
    #  - alpha
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    if: ${{ github.repository_owner == 'Koen-Schockaert' }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Build & publish Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish always

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            dist/**
            release/**
            out/**
