name: Build and Release

on:
  push:
    #branches:
    #  - main
    #  - beta
    #  - alpha
    tags:
      - 'v*'
      
permissions:
  contents: write
  packages: write

jobs:
  build:
    if: ${{ github.repository_owner == 'Koen-Schockaert' }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Package Electron app (create artifacts)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # create artifacts locally (don't publish yet)
          npx electron-builder --publish=never

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            release/build/**
            out/**
            dist/**

      - name: Publish Electron app (attach artifacts to GitHub release)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish=always
